#!/bin/sh
#SBATCH --job-name=doFuture-5
#SBATCH --time=8:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=240G
#SBATCH -o log/%x_%j_%A_%a.out
#SBATCH --mail-user=fred1515@hotmail.com
#SBATCH --mail-type=ALL
#SBATCH --output=message/%x_%j_%A_%a-result.txt
#SBATCH --error=message/%x_%j_%A_%a-error.txt
#SBATCH --exclusive
#SBATCH --account=def-fouimet
module load StdEnv/2023 r/4.3.1
export R_LIBS_USER="$HOME/R/x86_64-pc-linux-gnu-library/4.3"
export R_LIBS="$R_LIBS_USER"
Rscript -e 'batchtools::doJobCollection("/home/fouimet/WishartKDE/TempWishartKDE/.future/20260605_090439-6u3xzs/doFuture-5_208245165/jobs/joba78babba61be09a5a3ffab77c9d1c3c6.rds")'
